'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5466
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------




Imports Microsoft.VisualBasic
Imports System

Namespace My
	<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(), Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")> _
	Partial Friend NotInheritable Class Settings
		Inherits System.Configuration.ApplicationSettingsBase

		Private Shared defaultInstance As Settings = (CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New Settings()), Settings))

		Public Shared ReadOnly Property [Default]() As Settings
			Get
				Return defaultInstance
			End Get
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("40")> _
		Public Property DetectionMinIod() As Decimal
			Get
				Return (CDec(Me("DetectionMinIod")))
			End Get
			Set(ByVal value As Decimal)
				Me("DetectionMinIod") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("4000")> _
		Public Property DetectionMaxIod() As Decimal
			Get
				Return (CDec(Me("DetectionMaxIod")))
			End Get
			Set(ByVal value As Decimal)
				Me("DetectionMaxIod") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("51")> _
		Public Property DetectionFaceConfidenceThreshold() As Decimal
			Get
				Return (CDec(Me("DetectionFaceConfidenceThreshold")))
			End Get
			Set(ByVal value As Decimal)
				Me("DetectionFaceConfidenceThreshold") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("8")> _
		Public Property MaxThreadCount() As Decimal
			Get
				Return (CDec(Me("MaxThreadCount")))
			End Get
			Set(ByVal value As Decimal)
				Me("MaxThreadCount") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("128")> _
		Public Property ExtractionFaceQualityThreshold() As Decimal
			Get
				Return (CDec(Me("ExtractionFaceQualityThreshold")))
			End Get
			Set(ByVal value As Decimal)
				Me("ExtractionFaceQualityThreshold") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("5")> _
		Public Property ExtractionMaxRecordsPerTemplate() As Decimal
			Get
				Return (CDec(Me("ExtractionMaxRecordsPerTemplate")))
			End Get
			Set(ByVal value As Decimal)
				Me("ExtractionMaxRecordsPerTemplate") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("48")> _
		Public Property IdentificationMatchingThreshold() As Decimal
			Get
				Return (CDec(Me("IdentificationMatchingThreshold")))
			End Get
			Set(ByVal value As Decimal)
				Me("IdentificationMatchingThreshold") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("10")> _
		Public Property IdentificationMaxBestMatchCount() As Decimal
			Get
				Return (CDec(Me("IdentificationMaxBestMatchCount")))
			End Get
			Set(ByVal value As Decimal)
				Me("IdentificationMaxBestMatchCount") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("False")> _
		Public Property MiscFlipImage() As Boolean
			Get
				Return (CBool(Me("MiscFlipImage")))
			End Get
			Set(ByVal value As Boolean)
				Me("MiscFlipImage") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("10")> _
		Public Property MiscMaxTreeNodeCount() As Decimal
			Get
				Return (CDec(Me("MiscMaxTreeNodeCount")))
			End Get
			Set(ByVal value As Decimal)
				Me("MiscMaxTreeNodeCount") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("15")> _
		Public Property DetectionMaxRollAngleDeviation() As Decimal
			Get
				Return (CDec(Me("DetectionMaxRollAngleDeviation")))
			End Get
			Set(ByVal value As Decimal)
				Me("DetectionMaxRollAngleDeviation") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("Medium")> _
		Public Property ExtractionEnrollmentTemplateSize() As Global.Neurotec.Biometrics.NleTemplateSize
			Get
				Return (CType(Me("ExtractionEnrollmentTemplateSize"), Global.Neurotec.Biometrics.NleTemplateSize))
			End Get
			Set(ByVal value As Neurotec.Biometrics.NleTemplateSize)
				Me("ExtractionEnrollmentTemplateSize") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("Medium")> _
		Public Property ExtractionIdentificationTemplateSize() As Global.Neurotec.Biometrics.NleTemplateSize
			Get
				Return (CType(Me("ExtractionIdentificationTemplateSize"), Global.Neurotec.Biometrics.NleTemplateSize))
			End Get
			Set(ByVal value As Neurotec.Biometrics.NleTemplateSize)
				Me("ExtractionIdentificationTemplateSize") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("250")> _
		Public Property MiscDisplayTime() As Integer
			Get
				Return (CInt(Fix(Me("MiscDisplayTime"))))
			End Get
			Set(ByVal value As Integer)
				Me("MiscDisplayTime") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("")> _
		Public Property Instances() As String
			Get
				Return (CStr(Me("Instances")))
			End Get
			Set(ByVal value As String)
				Me("Instances") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("1002")> _
		Public Property ListenPort() As Integer
			Get
				Return (CInt(Fix(Me("ListenPort"))))
			End Get
			Set(ByVal value As Integer)
				Me("ListenPort") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("False")> _
		Public Property Synchronize() As Boolean
			Get
				Return (CBool(Me("Synchronize")))
			End Get
			Set(ByVal value As Boolean)
				Me("Synchronize") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("15")> _
		Public Property MaxYawAngle() As Short
			Get
				Return (CShort(Fix(Me("MaxYawAngle"))))
			End Get
			Set(ByVal value As Short)
				Me("MaxYawAngle") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("3")> _
		Public Property FaceDetectionScale() As Integer
			Get
				Return (CInt(Fix(Me("FaceDetectionScale"))))
			End Get
			Set(ByVal value As Integer)
				Me("FaceDetectionScale") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("0")> _
		Public Property FaceRollAngleBase() As Short
			Get
				Return (CShort(Fix(Me("FaceRollAngleBase"))))
			End Get
			Set(ByVal value As Short)
				Me("FaceRollAngleBase") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("False")> _
		Public Property DetectMoreFaces() As Boolean
			Get
				Return (CBool(Me("DetectMoreFaces")))
			End Get
			Set(ByVal value As Boolean)
				Me("DetectMoreFaces") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("False")> _
		Public Property ExtractionDetectGener() As Boolean
			Get
				Return (CBool(Me("ExtractionDetectGener")))
			End Get
			Set(ByVal value As Boolean)
				Me("ExtractionDetectGener") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("False")> _
		Public Property ExtractionDetectExpression() As Boolean
			Get
				Return (CBool(Me("ExtractionDetectExpression")))
			End Get
			Set(ByVal value As Boolean)
				Me("ExtractionDetectExpression") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("False")> _
		Public Property ExtractionDetectBlink() As Boolean
			Get
				Return (CBool(Me("ExtractionDetectBlink")))
			End Get
			Set(ByVal value As Boolean)
				Me("ExtractionDetectBlink") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("False")> _
		Public Property ExtractionDetectMouthOpen() As Boolean
			Get
				Return (CBool(Me("ExtractionDetectMouthOpen")))
			End Get
			Set(ByVal value As Boolean)
				Me("ExtractionDetectMouthOpen") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("False")> _
		Public Property ExtractionDetectGlasses() As Boolean
			Get
				Return (CBool(Me("ExtractionDetectGlasses")))
			End Get
			Set(ByVal value As Boolean)
				Me("ExtractionDetectGlasses") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("False")> _
		Public Property ExtractionDetectDarkGlasses() As Boolean
			Get
				Return (CBool(Me("ExtractionDetectDarkGlasses")))
			End Get
			Set(ByVal value As Boolean)
				Me("ExtractionDetectDarkGlasses") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("5")> _
		Public Property ExtractionGenderConfidenceThreshold() As Byte
			Get
				Return (CByte(Me("ExtractionGenderConfidenceThreshold")))
			End Get
			Set(ByVal value As Byte)
				Me("ExtractionGenderConfidenceThreshold") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("5")> _
		Public Property ExtractionExpressionConfidenceThreshold() As Byte
			Get
				Return (CByte(Me("ExtractionExpressionConfidenceThreshold")))
			End Get
			Set(ByVal value As Byte)
				Me("ExtractionExpressionConfidenceThreshold") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("5")> _
		Public Property ExtractionBlinkConfidenceThreshold() As Byte
			Get
				Return (CByte(Me("ExtractionBlinkConfidenceThreshold")))
			End Get
			Set(ByVal value As Byte)
				Me("ExtractionBlinkConfidenceThreshold") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("5")> _
		Public Property ExtractionMouthOpenConfidenceThreshold() As Byte
			Get
				Return (CByte(Me("ExtractionMouthOpenConfidenceThreshold")))
			End Get
			Set(ByVal value As Byte)
				Me("ExtractionMouthOpenConfidenceThreshold") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("5")> _
		Public Property ExtractionGlassesConfidenceThreshold() As Byte
			Get
				Return (CByte(Me("ExtractionGlassesConfidenceThreshold")))
			End Get
			Set(ByVal value As Byte)
				Me("ExtractionGlassesConfidenceThreshold") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("5")> _
		Public Property ExtractionDarkGlassesConfidenceThreshold() As Byte
			Get
				Return (CByte(Me("ExtractionDarkGlassesConfidenceThreshold")))
			End Get
			Set(ByVal value As Byte)
				Me("ExtractionDarkGlassesConfidenceThreshold") = value
			End Set
		End Property
	End Class
End Namespace