#ifndef NE_SEGMENTER_PARAMS_H_INCLUDED
#define NE_SEGMENTER_PARAMS_H_INCLUDED

#include <NParameters.h>

#define NESP_HORIZONTAL_MARGIN        10001
#define NESP_VERTICAL_MARGIN          10002
#define NESP_UPPER_EYELID_MASK_VALUE  10011
#define NESP_SCLERA_MASK_VALUE        10012
#define NESP_LOWER_EYELID_MASK_VALUE  10013

#define NESP_QUALITY_THRESHOLD                     20001
#define NESP_GRAY_LEVEL_SPREAD_THRESHOLD           20002
#define NESP_IRIS_SIZE_THRESHOLD                   20003
#define NESP_PUPIL_IRIS_RATIO_THRESHOLD            20004
#define NESP_USABLE_IRIS_AREA_THRESHOLD            20005
#define NESP_IRIS_SCLERA_CONTRAST_THRESHOLD        20006
#define NESP_IRIS_PUPIL_CONTRAST_THRESHOLD         20007
#define NESP_IRIS_SCLERA_BOUNDARY_SHAPE_THRESHOLD  20008
#define NESP_IRIS_PUPIL_BOUNDARY_SHAPE_THRESHOLD   20009
#define NESP_MARGIN_THRESHOLD                      20010
#define NESP_SHARPNESS_THRESHOLD                   20011
#define NESP_SIGNAL_TO_NOISE_RATIO_THRESHOLD       20013
#define NESP_INTERLACE_THRESHOLD                   20017

#endif // !NE_SEGMENTER_PARAMS_H_INCLUDED
