#ifndef NF_MATCHER_PARAMS_HPP_INCLUDED
#define NF_MATCHER_PARAMS_HPP_INCLUDED

#include <NParameters.hpp>
namespace Neurotec { namespace Biometrics
{
#include <NFMatcherParams.h>
}}

namespace Neurotec { namespace Biometrics
{
#undef NFMP_MATCHING_THRESHOLD
#undef NFMP_MAXIMAL_ROTATION
#undef NFMP_MATCHING_SPEED
#undef NFMP_MODE

#undef NFM_MODE_GENERAL
#undef NFM_MODE_DIGITALPERSONA_UAREU
#undef NFM_MODE_BIOMETRIKA_FX2000
#undef NFM_MODE_BIOMETRIKA_FX3000
#undef NFM_MODE_KEYTRONIC_SECUREDESKTOP
#undef NFM_MODE_IDENTIX_TOUCHVIEW
#undef NFM_MODE_IDENTIX_DFR2090
#undef NFM_MODE_PRECISEBIOMETRICS_100CS
#undef NFM_MODE_UPEK_TOUCHCHIP
#undef NFM_MODE_IDENTICATORTECHNOLOGY_DF90
#undef NFM_MODE_AUTHENTEC_AFS2
#undef NFM_MODE_AUTHENTEC_AES4000
#undef NFM_MODE_AUTHENTEC_AES2501B
#undef NFM_MODE_ATMEL_FINGERCHIP
#undef NFM_MODE_BMF_BLP100
#undef NFM_MODE_SECUGEN_HAMSTER
#undef NFM_MODE_ETHENTICA
#undef NFM_MODE_CROSSMATCH_VERIFIER300
#undef NFM_MODE_NITGEN_FINGKEY_HAMSTER
#undef NFM_MODE_TESTECH_BIOI
#undef NFM_MODE_DIGENT_IZZIX
#undef NFM_MODE_STARTEK_FM200
#undef NFM_MODE_FUJITSU_MBF200
#undef NFM_MODE_FUTRONIC_FS80
#undef NFM_MODE_LIGHTUNING_LTTC500
#undef NFM_MODE_TACOMA_CMOS

const NUShort NFMP_MATCHING_THRESHOLD = 200;
const NUShort NFMP_MAXIMAL_ROTATION = 201;
const NUShort NFMP_MATCHING_SPEED = 220;
const NUShort NFMP_MODE = 1000;

const NInt NFM_MODE_GENERAL = 0;
const NInt NFM_MODE_DIGITALPERSONA_UAREU = 100;
const NInt NFM_MODE_BIOMETRIKA_FX2000 = 200;
const NInt NFM_MODE_BIOMETRIKA_FX3000 = 201;
const NInt NFM_MODE_KEYTRONIC_SECUREDESKTOP = 300;
const NInt NFM_MODE_IDENTIX_TOUCHVIEW = 400;
const NInt NFM_MODE_IDENTIX_DFR2090 = 401;
const NInt NFM_MODE_PRECISEBIOMETRICS_100CS = 500;
const NInt NFM_MODE_UPEK_TOUCHCHIP = 600;
const NInt NFM_MODE_IDENTICATORTECHNOLOGY_DF90 = 700;
const NInt NFM_MODE_AUTHENTEC_AFS2 = 800;
const NInt NFM_MODE_AUTHENTEC_AES4000 = 810;
const NInt NFM_MODE_AUTHENTEC_AES2501B = 811;
const NInt NFM_MODE_ATMEL_FINGERCHIP = 900;
const NInt NFM_MODE_BMF_BLP100 = 1000;
const NInt NFM_MODE_SECUGEN_HAMSTER = 1100;
const NInt NFM_MODE_ETHENTICA = 1200;
const NInt NFM_MODE_CROSSMATCH_VERIFIER300 = 1300;
const NInt NFM_MODE_NITGEN_FINGKEY_HAMSTER = 1400;
const NInt NFM_MODE_TESTECH_BIOI = 1500;
const NInt NFM_MODE_DIGENT_IZZIX = 1600;
const NInt NFM_MODE_STARTEK_FM200 = 1700;
const NInt NFM_MODE_FUJITSU_MBF200 = 1800;
const NInt NFM_MODE_FUTRONIC_FS80 = 1900;
const NInt NFM_MODE_LIGHTUNING_LTTC500 = 2000;
const NInt NFM_MODE_TACOMA_CMOS = 2100;
}}

#endif // !NF_MATCHER_PARAMS_HPP_INCLUDED
