#ifndef NL_EXTRACTOR_PARAMS_HPP_INCLUDED
#define NL_EXTRACTOR_PARAMS_HPP_INCLUDED

#include <NParameters.hpp>
namespace Neurotec { namespace Biometrics
{
#include <NLExtractorParams.h>
}}

namespace Neurotec { namespace Biometrics
{
#undef NLEP_MIN_IOD
#undef NLEP_MAX_IOD
#undef NLEP_FACE_CONFIDENCE_THRESHOLD
#undef NLEP_FAVOR_LARGEST_FACE
#undef NLEP_MAX_ROLL_ANGLE_DEVIATION
#undef NLEP_MAX_YAW_ANGLE_DEVIATION
#undef NLEP_DETECT_MORE_FACES
#undef NLEP_FACE_DETECTION_SCALE_COUNT
#undef NLEP_FACE_ROLL_ANGLE_BASE
#undef NLEP_DETECT_ALL_FEATURE_POINTS
#undef NLEP_DETECT_BASE_FEATURE_POINTS
#undef NLEP_FACE_QUALITY_THRESHOLD
#undef NLEP_TEMPLATE_SIZE
#undef NLEP_USE_LIVENESS_CHECK
#undef NLEP_LIVENESS_THRESHOLD
#undef NLEP_MAX_RECORDS_PER_TEMPLATE
#undef NLEP_MAX_STREAM_DURATION_IN_FRAMES
#undef NLEP_DETECT_GENDER
#undef NLEP_GENDER_CONFIDENCE_THRESHOLD
#undef NLEP_DETECT_GLASSES
#undef NLEP_GLASSES_CONFIDENCE_THRESHOLD
#undef NLEP_DETECT_DARK_GLASSES
#undef NLEP_DARK_GLASSES_CONFIDENCE_THRESHOLD
#undef NLEP_DETECT_EXPRESSION
#undef NLEP_EXPRESSION_CONFIDENCE_THRESHOLD
#undef NLEP_DETECT_BLINK
#undef NLEP_BLINK_CONFIDENCE_THRESHOLD
#undef NLEP_DETECT_MOUTH_OPEN
#undef NLEP_MOUTH_OPEN_CONFIDENCE_THRESHOLD

const NUShort NLEP_MIN_IOD = 10101;
const NUShort NLEP_MAX_IOD = 10102;
const NUShort NLEP_FACE_CONFIDENCE_THRESHOLD = 10103;
const NUShort NLEP_FAVOR_LARGEST_FACE = 10104;
const NUShort NLEP_MAX_ROLL_ANGLE_DEVIATION = 10105;
const NUShort NLEP_MAX_YAW_ANGLE_DEVIATION = 10109;
const NUShort NLEP_DETECT_MORE_FACES = 10110;
const NUShort NLEP_FACE_DETECTION_SCALE_COUNT = 10111;
const NUShort NLEP_FACE_ROLL_ANGLE_BASE = 10117;
const NUShort NLEP_DETECT_ALL_FEATURE_POINTS = 10250;
const NUShort NLEP_DETECT_BASE_FEATURE_POINTS = 10255;
const NUShort NLEP_FACE_QUALITY_THRESHOLD = 10350;
const NUShort NLEP_TEMPLATE_SIZE = 10360;
const NUShort NLEP_USE_LIVENESS_CHECK = 10402;
const NUShort NLEP_LIVENESS_THRESHOLD = 10403;
const NUShort NLEP_MAX_RECORDS_PER_TEMPLATE = 10408;
const NUShort NLEP_MAX_STREAM_DURATION_IN_FRAMES = 10409;
const NUShort NLEP_DETECT_GENDER = 10451;
const NUShort NLEP_GENDER_CONFIDENCE_THRESHOLD = 10452;
const NUShort NLEP_DETECT_GLASSES = 10453;
const NUShort NLEP_GLASSES_CONFIDENCE_THRESHOLD = 10454;
const NUShort NLEP_DETECT_DARK_GLASSES = 10455;
const NUShort NLEP_DARK_GLASSES_CONFIDENCE_THRESHOLD = 10456;
const NUShort NLEP_DETECT_EXPRESSION = 10457;
const NUShort NLEP_EXPRESSION_CONFIDENCE_THRESHOLD = 10458;
const NUShort NLEP_DETECT_BLINK = 10459;
const NUShort NLEP_BLINK_CONFIDENCE_THRESHOLD = 10460;
const NUShort NLEP_DETECT_MOUTH_OPEN = 10461;
const NUShort NLEP_MOUTH_OPEN_CONFIDENCE_THRESHOLD = 10462;
}}

#endif // !NL_EXTRACTOR_PARAMS_HPP_INCLUDED
