#ifndef N_MATCHER_PARAMS_HPP_INCLUDED
#define N_MATCHER_PARAMS_HPP_INCLUDED

#include <NParameters.hpp>
namespace Neurotec { namespace Biometrics
{
#include <NMatcherParams.h>
}}

namespace Neurotec { namespace Biometrics
{
#undef NM_PART_NONE
#undef NM_PART_FINGERS
#undef NM_PART_FACES
#undef NM_PART_IRISES
#undef NM_PART_PALMS

#undef NMP_MATCHING_THRESHOLD
#undef NMP_FUSION_TYPE
#undef NMP_FACES_MATCHING_THRESHOLD
#undef NMP_FACES_MATCHING_THRESHOLD_NEW
#undef NMP_IRISES_MATCHING_THRESHOLD

#undef NMP_FINGERS_MAXIMAL_ROTATION
#undef NMP_FINGERS_MATCHING_SPEED
#undef NMP_FINGERS_FILL_FULL_MATCHING_DETAILS
#undef NMP_FINGERS_MODE
#undef NMP_FINGERS_MIN_MATCHED_COUNT
#undef NMP_FINGERS_MIN_MATCHED_COUNT_THRESHOLD

#undef NMP_FACES_MATCHING_SPEED

#undef NMP_IRISES_MATCHING_SPEED
#undef NMP_IRISES_MAXIMAL_ROTATION
#undef NMP_IRISES_MIN_MATCHED_COUNT
#undef NMP_IRISES_MIN_MATCHED_COUNT_THRESHOLD

#undef NMP_PALMS_MAXIMAL_ROTATION
#undef NMP_PALMS_MATCHING_SPEED
#undef NMP_PALMS_FILL_FULL_MATCHING_DETAILS
#undef NMP_PALMS_MIN_MATCHED_COUNT
#undef NMP_PALMS_MIN_MATCHED_COUNT_THRESHOLD

#undef NMP_VOICES_UNIQUE_PHRASES_ONLY

#undef NM_FINGERS_MODE_GENERAL
#undef NM_FINGERS_MODE_DIGITALPERSONA_UAREU
#undef NM_FINGERS_MODE_BIOMETRIKA_FX2000
#undef NM_FINGERS_MODE_BIOMETRIKA_FX3000
#undef NM_FINGERS_MODE_KEYTRONIC_SECUREDESKTOP
#undef NM_FINGERS_MODE_IDENTIX_TOUCHVIEW
#undef NM_FINGERS_MODE_IDENTIX_DFR2090
#undef NM_FINGERS_MODE_PRECISEBIOMETRICS_100CS
#undef NM_FINGERS_MODE_UPEK_TOUCHCHIP
#undef NM_FINGERS_MODE_IDENTICATORTECHNOLOGY_DF90
#undef NM_FINGERS_MODE_AUTHENTEC_AFS2
#undef NM_FINGERS_MODE_AUTHENTEC_AES4000
#undef NM_FINGERS_MODE_AUTHENTEC_AES2501B
#undef NM_FINGERS_MODE_ATMEL_FINGERCHIP
#undef NM_FINGERS_MODE_BMF_BLP100
#undef NM_FINGERS_MODE_SECUGEN_HAMSTER
#undef NM_FINGERS_MODE_ETHENTICA
#undef NM_FINGERS_MODE_CROSSMATCH_VERIFIER300
#undef NM_FINGERS_MODE_NITGEN_FINGKEY_HAMSTER
#undef NM_FINGERS_MODE_TESTECH_BIOI
#undef NM_FINGERS_MODE_DIGENT_IZZIX
#undef NM_FINGERS_MODE_STARTEK_FM200
#undef NM_FINGERS_MODE_FUJITSU_MBF200
#undef NM_FINGERS_MODE_FUTRONIC_FS80
#undef NM_FINGERS_MODE_LIGHTUNING_LTTC500
#undef NM_FINGERS_MODE_TACOMA_CMOS

N_DEPRECATED("constant is deprecated")
const NUShort NM_PART_NONE    =  0;
N_DEPRECATED("constant is deprecated")
const NUShort NM_PART_FINGERS = 10;
N_DEPRECATED("constant is deprecated")
const NUShort NM_PART_FACES   = 20;
N_DEPRECATED("constant is deprecated")
const NUShort NM_PART_IRISES  = 30;
N_DEPRECATED("constant is deprecated")
const NUShort NM_PART_PALMS   = 40;

const NUShort NMP_MATCHING_THRESHOLD           = 100;
const NUShort NMP_FUSION_TYPE                  = 200;
const NUShort NMP_FACES_MATCHING_THRESHOLD     = 210;
const NUShort NMP_FACES_MATCHING_THRESHOLD_NEW = 215;
const NUShort NMP_IRISES_MATCHING_THRESHOLD    = 220;

const NUShort NMP_FINGERS_MAXIMAL_ROTATION            = NMP_FINGERS_MATCHER_BASE +  201;
const NUShort NMP_FINGERS_MATCHING_SPEED              = NMP_FINGERS_MATCHER_BASE +  220;
const NUShort NMP_FINGERS_FILL_FULL_MATCHING_DETAILS  = NMP_FINGERS_MATCHER_BASE +  900;
const NUShort NMP_FINGERS_MODE                        = NMP_FINGERS_MATCHER_BASE + 1000;
const NUShort NMP_FINGERS_MIN_MATCHED_COUNT           = NMP_FINGERS_MATCHER_BASE + 1201;
const NUShort NMP_FINGERS_MIN_MATCHED_COUNT_THRESHOLD = NMP_FINGERS_MATCHER_BASE + 1202;

const NUShort NMP_FACES_MATCHING_SPEED              = NMP_FACES_MATCHER_BASE +    1;

const NUShort NMP_IRISES_MATCHING_SPEED              = NMP_IRISES_MATCHER_BASE +    1;
const NUShort NMP_IRISES_MAXIMAL_ROTATION            = NMP_IRISES_MATCHER_BASE +    2;
const NUShort NMP_IRISES_MIN_MATCHED_COUNT           = NMP_IRISES_MATCHER_BASE + 1201;
const NUShort NMP_IRISES_MIN_MATCHED_COUNT_THRESHOLD = NMP_IRISES_MATCHER_BASE + 1202;

const NUShort NMP_PALMS_MAXIMAL_ROTATION            = NMP_PALMS_MATCHER_BASE +  201;
const NUShort NMP_PALMS_MATCHING_SPEED              = NMP_PALMS_MATCHER_BASE +  220;
const NUShort NMP_PALMS_FILL_FULL_MATCHING_DETAILS  = NMP_PALMS_MATCHER_BASE +  900;
const NUShort NMP_PALMS_MIN_MATCHED_COUNT           = NMP_PALMS_MATCHER_BASE + 1201;
const NUShort NMP_PALMS_MIN_MATCHED_COUNT_THRESHOLD = NMP_PALMS_MATCHER_BASE + 1202;

const NUShort NMP_VOICES_UNIQUE_PHRASES_ONLY = NMP_VOICES_MATCHER_BASE +    2;

const NInt NM_FINGERS_MODE_GENERAL = 0;
const NInt NM_FINGERS_MODE_DIGITALPERSONA_UAREU = 100;
const NInt NM_FINGERS_MODE_BIOMETRIKA_FX2000 = 200;
const NInt NM_FINGERS_MODE_BIOMETRIKA_FX3000 = 201;
const NInt NM_FINGERS_MODE_KEYTRONIC_SECUREDESKTOP = 300;
const NInt NM_FINGERS_MODE_IDENTIX_TOUCHVIEW = 400;
const NInt NM_FINGERS_MODE_IDENTIX_DFR2090 = 401;
const NInt NM_FINGERS_MODE_PRECISEBIOMETRICS_100CS = 500;
const NInt NM_FINGERS_MODE_UPEK_TOUCHCHIP = 600;
const NInt NM_FINGERS_MODE_IDENTICATORTECHNOLOGY_DF90 = 700;
const NInt NM_FINGERS_MODE_AUTHENTEC_AFS2 = 800;
const NInt NM_FINGERS_MODE_AUTHENTEC_AES4000 = 810;
const NInt NM_FINGERS_MODE_AUTHENTEC_AES2501B = 811;
const NInt NM_FINGERS_MODE_ATMEL_FINGERCHIP = 900;
const NInt NM_FINGERS_MODE_BMF_BLP100 = 1000;
const NInt NM_FINGERS_MODE_SECUGEN_HAMSTER = 1100;
const NInt NM_FINGERS_MODE_ETHENTICA = 1200;
const NInt NM_FINGERS_MODE_CROSSMATCH_VERIFIER300 = 1300;
const NInt NM_FINGERS_MODE_NITGEN_FINGKEY_HAMSTER = 1400;
const NInt NM_FINGERS_MODE_TESTECH_BIOI = 1500;
const NInt NM_FINGERS_MODE_DIGENT_IZZIX = 1600;
const NInt NM_FINGERS_MODE_STARTEK_FM200 = 1700;
const NInt NM_FINGERS_MODE_FUJITSU_MBF200 = 1800;
const NInt NM_FINGERS_MODE_FUTRONIC_FS80 = 1900;
const NInt NM_FINGERS_MODE_LIGHTUNING_LTTC500 = 2000;
const NInt NM_FINGERS_MODE_TACOMA_CMOS = 2100;
}}

#endif // !N_MATCHER_PARAMS_HPP_INCLUDED
