#ifndef N_SURVEILLANCE_PARAMS_HPP_INCLUDED
#define N_SURVEILLANCE_PARAMS_HPP_INCLUDED

#include <NParameters.hpp>
namespace Neurotec { namespace Surveillance
{
#include <NSurveillanceParams.h>
}}

namespace Neurotec { namespace Surveillance
{
#undef NSP_MAX_THREAD_COUNT
#undef NSP_DETECTION_MIN_IOD
#undef NSP_DETECTION_MAX_IOD
#undef NSP_DETECTION_FACE_CONFIDENCE_THRESHOLD
#undef NSP_DETECTION_MAX_ROLL_ANGLE_DEVIATION
#undef NSP_DETECTION_MAX_YAW_ANGLE_DEVIATION
#undef NSP_DETECTION_DETECT_MORE_FACES
#undef NSP_DETECTION_FACE_DETECTION_SCALE_COUNT
#undef NSP_DETECTION_FACE_ROLL_ANGLE_BASE
#undef NSP_EXTRACTION_FACE_QUALITY_THRESHOLD
#undef NSP_EXTRACTION_MAX_RECORDS_PER_TEMPLATE
#undef NSP_EXTRACTION_ENROLLMENT_TEMPLATE_SIZE
#undef NSP_EXTRACTION_IDENTIFICATION_TEMPLATE_SIZE
#undef NSP_EXTRACTION_DETECT_GENDER
#undef NSP_EXTRACTION_GENDER_CONFIDENCE_THRESHOLD
#undef NSP_IDENTIFICATION_MATCHING_THRESHOLD
#undef NSP_IDENTIFICATION_MAX_BEST_MATCH_COUNT

const NUShort NSP_MAX_THREAD_COUNT = 10001;
const NUShort NSP_DETECTION_MIN_IOD = 10102;
const NUShort NSP_DETECTION_MAX_IOD = 10103;
const NUShort NSP_DETECTION_FACE_CONFIDENCE_THRESHOLD = 10104;
const NUShort NSP_DETECTION_MAX_ROLL_ANGLE_DEVIATION = 10105;
const NUShort NSP_DETECTION_MAX_YAW_ANGLE_DEVIATION = 10106;
const NUShort NSP_DETECTION_DETECT_MORE_FACES = 10107;
const NUShort NSP_DETECTION_FACE_DETECTION_SCALE_COUNT = 10108;
const NUShort NSP_DETECTION_FACE_ROLL_ANGLE_BASE = 10109;
const NUShort NSP_EXTRACTION_FACE_QUALITY_THRESHOLD = 10202;
const NUShort NSP_EXTRACTION_MAX_RECORDS_PER_TEMPLATE = 10203;
const NUShort NSP_EXTRACTION_ENROLLMENT_TEMPLATE_SIZE = 10204;
const NUShort NSP_EXTRACTION_IDENTIFICATION_TEMPLATE_SIZE = 10205;
const NUShort NSP_EXTRACTION_DETECT_GENDER = 10210;
const NUShort NSP_EXTRACTION_GENDER_CONFIDENCE_THRESHOLD = 10211;
const NUShort NSP_IDENTIFICATION_MATCHING_THRESHOLD = 10302;
const NUShort NSP_IDENTIFICATION_MAX_BEST_MATCH_COUNT = 10303;
}}

#endif // !N_SURVEILLANCE_PARAMS_HPP_INCLUDED
