#ifndef N_SURVEILLANCE_PARAMS_H_INCLUDED
#define N_SURVEILLANCE_PARAMS_H_INCLUDED

#include <NParameters.h>

#ifdef N_CPP
extern "C"
{
#endif

#define NSP_MAX_THREAD_COUNT                              10001

#define NSP_DETECTION_MIN_IOD                             10102
#define NSP_DETECTION_MAX_IOD                             10103
#define NSP_DETECTION_FACE_CONFIDENCE_THRESHOLD           10104
#define NSP_DETECTION_MAX_ROLL_ANGLE_DEVIATION            10105
#define NSP_DETECTION_MAX_YAW_ANGLE_DEVIATION             10106
#define NSP_DETECTION_DETECT_MORE_FACES                   10107
#define NSP_DETECTION_FACE_DETECTION_SCALE_COUNT          10108
#define NSP_DETECTION_FACE_ROLL_ANGLE_BASE                10109

#define NSP_EXTRACTION_FACE_QUALITY_THRESHOLD             10202
#define NSP_EXTRACTION_MAX_RECORDS_PER_TEMPLATE           10203
#define NSP_EXTRACTION_ENROLLMENT_TEMPLATE_SIZE           10204
#define NSP_EXTRACTION_IDENTIFICATION_TEMPLATE_SIZE       10205

#define NSP_EXTRACTION_DETECT_GENDER                      10210
#define NSP_EXTRACTION_GENDER_CONFIDENCE_THRESHOLD        10211
#define NSP_EXTRACTION_DETECT_EXPRESSION                  10212
#define NSP_EXTRACTION_EXPRESSION_CONFIDENCE_THRESHOLD    10213
#define NSP_EXTRACTION_DETECT_BLINK                       10214
#define NSP_EXTRACTION_BLINK_CONFIDENCE_THRESHOLD         10215
#define NSP_EXTRACTION_DETECT_MOUTH_OPEN                  10216
#define NSP_EXTRACTION_MOUTH_OPEN_CONFIDENCE_THRESHOLD    10217
#define NSP_EXTRACTION_DETECT_GLASSES                     10218
#define NSP_EXTRACTION_GLASSES_CONFIDENCE_THRESHOLD       10219
#define NSP_EXTRACTION_DETECT_DARK_GLASSES                10220
#define NSP_EXTRACTION_DARK_GLASSES_CONFIDENCE_THRESHOLD  10221

#define NSP_IDENTIFICATION_MATCHING_THRESHOLD             10302
#define NSP_IDENTIFICATION_MAX_BEST_MATCH_COUNT           10303

#ifdef N_CPP
}
#endif

#endif // !N_SURVEILLANCE_PARAMS_H_INCLUDED
